import { tv, type TVVariantProps } from "../../utils/tv";

export const aiPromptBoxVariants = tv({
  slots: {
    root: [
      "group/prompt relative flex flex-col gap-[var(--ds-spacing-2)]",
      "rounded-[var(--ds-radius-xl)]",
      "border border-solid border-[color:var(--ds-border-default)]",
      "bg-[color:var(--ds-bg-elevated,var(--ds-color-neutral-50))]",
      "shadow-[var(--ds-shadow-sm,0_1px_2px_0_rgba(0,0,0,0.05))]",
      "p-[var(--ds-spacing-3)]",
      "transition-[border-color,box-shadow]",
      "duration-[var(--ds-motion-duration-fast,150ms)]",
      "motion-reduce:transition-none",
      "focus-within:border-[color:var(--ds-color-focus-ring)]",
      "focus-within:shadow-[0_0_0_3px_color-mix(in_oklch,var(--ds-color-focus-ring)_25%,transparent)]",
      "data-[loading=true]:animate-pulse",
      "motion-reduce:data-[loading=true]:animate-none",
    ],
    suggestions: [
      "flex flex-wrap gap-[var(--ds-spacing-2)]",
    ],
    suggestionChip: [
      "inline-flex items-center",
      "px-[var(--ds-spacing-3)] py-[var(--ds-spacing-1)]",
      "rounded-[var(--ds-radius-pill)]",
      "border border-solid border-[color:var(--ds-border-default)]",
      "bg-[color:var(--ds-bg-muted,transparent)]",
      "text-[length:var(--ds-font-size-body-sm)]",
      "text-[color:var(--ds-text-secondary)]",
      "cursor-pointer select-none",
      "transition-colors",
      "duration-[var(--ds-motion-duration-fast,150ms)]",
      "hover:text-[color:var(--ds-text-primary)]",
      "hover:bg-[color:var(--ds-bg-elevated,transparent)]",
      "focus-visible:outline-2 focus-visible:outline-offset-2",
      "focus-visible:outline-[color:var(--ds-color-focus-ring)]",
    ],
    attachmentRow: [
      "flex flex-wrap gap-[var(--ds-spacing-2)]",
    ],
    attachmentChip: [
      "inline-flex items-center gap-[var(--ds-spacing-2)]",
      "px-[var(--ds-spacing-2_5)] py-[var(--ds-spacing-1)]",
      "rounded-[var(--ds-radius-md)]",
      "border border-solid border-[color:var(--ds-border-default)]",
      "bg-[color:var(--ds-bg-muted,transparent)]",
      "text-[length:var(--ds-font-size-body-xs)]",
      "text-[color:var(--ds-text-primary)]",
    ],
    textarea: [
      "w-full resize-none bg-transparent outline-none",
      "text-[length:var(--ds-font-size-body-md)]",
      "text-[color:var(--ds-text-primary)]",
      "leading-[var(--ds-font-line-height-relaxed,1.5)]",
      "placeholder:text-[color:var(--ds-text-placeholder,var(--ds-text-secondary))]",
      "font-[family-name:var(--ds-font-family-sans)]",
      "min-h-[var(--ds-spacing-16)]",
      "max-h-[var(--ds-spacing-72)]",
    ],
    footer: [
      "flex items-center justify-between gap-[var(--ds-spacing-3)]",
      "pt-[var(--ds-spacing-1)]",
    ],
    footerLeft: ["flex items-center gap-[var(--ds-spacing-2)]"],
    footerRight: ["flex items-center gap-[var(--ds-spacing-3)]"],
    modelBadge: [
      "inline-flex items-center gap-[var(--ds-spacing-1)]",
      "px-[var(--ds-spacing-2)] py-[var(--ds-spacing-0_5)]",
      "rounded-[var(--ds-radius-sm)]",
      "border border-solid border-[color:var(--ds-border-default)]",
      "text-[length:var(--ds-font-size-body-xs)]",
      "text-[color:var(--ds-text-secondary)]",
      "font-[family-name:var(--ds-font-family-mono)]",
    ],
    counter: [
      "text-[length:var(--ds-font-size-body-xs)]",
      "text-[color:var(--ds-text-secondary)]",
      "font-[family-name:var(--ds-font-family-mono)]",
      "tabular-nums",
      "data-[over=true]:text-[color:var(--ds-status-danger-fg,var(--ds-color-danger-500))]",
    ],
    submit: [
      "inline-flex items-center justify-center gap-[var(--ds-spacing-2)]",
      "h-[var(--ds-spacing-9)] px-[var(--ds-spacing-4)]",
      "rounded-[var(--ds-radius-md)]",
      "bg-[color:var(--ds-button-primary-bg,var(--ds-color-accent-500))]",
      "text-[color:var(--ds-button-primary-fg,var(--ds-color-neutral-1000))]",
      "text-[length:var(--ds-font-size-body-sm)]",
      "font-[var(--ds-font-weight-body-md,600)]",
      "cursor-pointer select-none",
      "transition-[opacity,transform]",
      "duration-[var(--ds-motion-duration-fast,150ms)]",
      "hover:not-disabled:opacity-[0.92]",
      "active:not-disabled:translate-y-[1px]",
      "disabled:cursor-not-allowed disabled:opacity-[var(--ds-opacity-disabled,0.5)]",
      "focus-visible:outline-2 focus-visible:outline-offset-2",
      "focus-visible:outline-[color:var(--ds-color-focus-ring)]",
    ],
    attachButton: [
      "inline-flex items-center justify-center",
      "h-[var(--ds-spacing-8)] w-[var(--ds-spacing-8)]",
      "rounded-[var(--ds-radius-md)]",
      "text-[color:var(--ds-text-secondary)]",
      "cursor-pointer",
      "transition-colors",
      "hover:text-[color:var(--ds-text-primary)]",
      "hover:bg-[color:var(--ds-bg-muted,transparent)]",
      "focus-visible:outline-2 focus-visible:outline-offset-2",
      "focus-visible:outline-[color:var(--ds-color-focus-ring)]",
    ],
  },
  variants: {
    variant: {
      default: {},
      minimal: {
        root: ["border-transparent shadow-none bg-transparent"],
      },
      bordered: {
        root: ["border-[color:var(--ds-border-strong)]"],
      },
    },
    size: {
      sm: { textarea: ["min-h-[var(--ds-spacing-10)]"] },
      md: {},
      lg: { textarea: ["min-h-[var(--ds-spacing-24)]"] },
    },
  },
  defaultVariants: {
    variant: "default",
    size: "md",
  },
});

export type AIPromptBoxVariantProps = TVVariantProps<typeof aiPromptBoxVariants>;
